insert into usuarios (nombre,`e-mail`) values ('Mariano','mariano@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Walter','walter@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Agus','agus@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Jenny','jenny@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Diego','diego@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Javier','javier@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Dario','dario@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Emilia','emilia@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Daniela','daniela@dh.com')
insert into usuarios (nombre,`e-mail`) values ('Hernan','hernano@dh.com')

insert into categoria (nombre) values ('Futbol')
insert into categoria (nombre) values ('Rugby')
insert into categoria (nombre) values ('Tenis')
insert into categoria (nombre) values ('Paddle')
insert into categoria (nombre) values ('Hockey')
insert into categoria (nombre) values ('Voley')
insert into categoria (nombre) values ('Handball')
insert into categoria (nombre) values ('Ciclismo')
insert into categoria (nombre) values ('Natacion')
insert into categoria (nombre) values ('Boxeo')

insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (1,111,'2001/01/01','2001/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (2,222,'2002/01/01','2002/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (3,333,'2003/01/01','2003/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (4,444,'2004/01/01','2004/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (5,555,'2005/01/01','2005/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (6,666,'2006/01/01','2006/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (7,777,'2007/01/01','2007/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (8,888,'2008/01/01','2008/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (9,999,'2009/01/01','2009/01/02', 'deporte')
insert into notas (usuario_id, titulo, fecha_creacion, fecha_ultima_modificacion, descripcion) values (10,101010,'2010/01/01','2010/01/02', 'deporte')

insert into notas_categoria (categoria_id, notas_id) values (1, 10)
insert into notas_categoria (categoria_id, notas_id) values (2, 9)
insert into notas_categoria (categoria_id, notas_id) values (3, 8)
insert into notas_categoria (categoria_id, notas_id) values (4, 7)
insert into notas_categoria (categoria_id, notas_id) values (5, 6)
insert into notas_categoria (categoria_id, notas_id) values (6, 5)
insert into notas_categoria (categoria_id, notas_id) values (7, 4)
insert into notas_categoria (categoria_id, notas_id) values (8, 3)
insert into notas_categoria (categoria_id, notas_id) values (9, 2)
insert into notas_categoria (categoria_id, notas_id) values (10, 1)
